name: Deploy

on:
  push:
    branches:
      - main
      - steven
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger BT Deploy
        run: |
          curl -k -X POST "https://139.196.165.140:17400/hook?access_key=${{ secrets.BT_WEBHOOK_KEY }}&param=${{ github.ref_name }}"
          echo "Deploy triggered for branch: ${{ github.ref_name }}"
